live: False
max_events: 100000
batch_size: 1000
h5:
  path1: /sdf/data/lcls/ds/tmo/
  path2: /scratch/xiangli/h5/
  name1: run
  name2: _corr.h5
log:
  path1: /sdf/data/lcls/ds/tmo/
  path2: /scratch/xiangli/log/

 
data:
  ## uniform:
  #   tpks_l:
  #     len: 10
  #     var: [mcp, u1]
  #   hit_l:
  #     len: 10
  #     fvar: [n]
  #     var: [z, y, t, m]

        #ragged_split:
        #tpks_l:
        #var: [mcp,u1,u2,v1,v2,w1,w2]  
        #tpks_s:
        #var: [mcp,u1,u2,v1,v2,w1,w2]


  ragged:
    # hit_s:
    #   var: [z, y, t]
    hit_l:
      var: [z, y, t, m]      

  x:
    scan: [var1, var2]
    bld: [gmd, xgmd]
    epics: [las_ip2_atm_dly]
  #   timing: ['280','281','282','dest']
  #   atm: [edge]
    

