nacc: 10

plots:
  #  t[l]_duck_goose:
  #      type: sigbkg1d
  #      plot_type: hist1d_func
  #      func_sig: {name: dream.custom.filter.duck_goose_arr, args1: ['hit_l:t', 'hit_l:n', 'timing:280'], args2:[1]}
  #      func_bkg: {name: dream.custom.filter.duck_goose_arr, args1: ['hit_l:t', 'hit_l:n', 'timing:281'], args2:[1]}
  #      arange_var: [0, 10000, 10]
  #      norm_type: 'sum'
  #      func_norm_sig: {name: dream.custom.filter.duck_goose_arr1, args1: ['bld:xgmd', 'timing:280'], args2:[1]}
  #      func_norm_bkg: {name: dream.custom.filter.duck_goose_arr1, args1: ['bld:xgmd', 'timing:281'], args2:[1]}

#    scan_t[l]_func:
#      type: scan_hist1d_func
#      func: {args1: ['hit_l:t']}
#      func_scan: {name: dream.custom.repeat.repeat, args1: ['scan:var1', 'hit_l:n']}
#      arange_var: [10000, 12000, 10]
#      decimal: 5       
 
    # t[l]_duck_goose_gatedOn_xy:
    #   type: sigbkg1d
    #   plot_type: hist1d_func
    #   func_sig: {name: dream.custom.filter.duck_goose_arr_gatedOn_xy, args1: ['hit_l:t', 'hit_l:n', 'timing:280', 'hit_l:y', 'hit_l:z'], args2:[1, -10, 10, -10, 10]}
    #   func_bkg: {name: dream.custom.filter.duck_goose_arr_gatedOn_xy, args1: ['hit_l:t', 'hit_l:n', 'timing:281', 'hit_l:y', 'hit_l:z'], args2:[1, -10, 10, -10, 10]}
    #   arange_var: {'hit_l:t': [4000, 6500, 10]}
    #   norm_type: 'sum'
    #   func_norm_sig: {name: dream.custom.filter.duck_goose_arr1, args1: ['bld:gmd', 'timing:280'], args2:[1]}
    #   func_norm_bkg: {name: dream.custom.filter.duck_goose_arr1, args1: ['bld:gmd', 'timing:281'], args2:[1]}


    # t[l]_duck_goose_gatedOn_xy_I+:
    #   type: sigbkg1d
    #   plot_type: hist1d_func
    #   func_sig: {name: dream.custom.filter.duck_goose_arr_gatedOn_xy, args1: ['hit_l:t', 'hit_l:n', 'timing:280', 'hit_l:y', 'hit_l:z'], args2:[1, -10, 10, -10, 10]}
    #   func_bkg: {name: dream.custom.filter.duck_goose_arr_gatedOn_xy, args1: ['hit_l:t', 'hit_l:n', 'timing:281', 'hit_l:y', 'hit_l:z'], args2:[1, -10, 10, -10, 10]}
    #   arange_var: {'hit_l:t': [10000, 11000, 10]}
    #   norm_type: 'sum'
    #   func_norm_sig: {name: dream.custom.filter.duck_goose_arr1, args1: ['bld:gmd', 'timing:280'], args2:[1]}
    #   func_norm_bkg: {name: dream.custom.filter.duck_goose_arr1, args1: ['bld:gmd', 'timing:281'], args2:[1]}

    
#    wf[l]:
#      type: multiline
#      y_offset: 100
#      var: ['wf_l:mcp', 'wf_l:u1', 'wf_l:u2', 'wf_l:v1', 'wf_l:v2', 'wf_l:w1', 'wf_l:w2']


    scan_count_func:
      type: scan_var_func
      func: {name: dream.custom.filter.n_gatedOn_abc, args1: ['hit_l:n', 'hit_l:t', 'hit_l:y', 'hit_l:z'], args2: [0, 3815, 0, 399, -43, 0.5]} #[3783, 3815, -1.69, 3.99, -4.3, 0.5]}
      func_scan: {args1: ['scan:var1']}
      decimal: 5     

    padded[l]:
      type: multiline
      y_offset: 1600
      var: ['pdd_l:mcp', 'pdd_l:u1', 'pdd_l:u2', 'pdd_l:v1', 'pdd_l:v2', 'pdd_l:w1', 'pdd_l:w2']      
      
    n[l]_rollavg:
      type: rollavg
      var: 'hit_l:n'
      window: {'w1':1000, 'w2':1000}
         
    n[l]_Ar_rollavg:
      type: rollavg_func
      func: {name: dream.custom.filter.gate1D_count, args1: ['hit_l:t'], args2: [5080, 5120]}
      window: {'w1':1000, 'w2':1000}   
        
    t[l]:
      type: hist1d
      arange: {'hit_l:t': [0, 15000, 1]}
    
    x-y[l]:
      type: hist2d
      arange: {'hit_l:y': [-65, 65, 2], 'hit_l:z': [-65, 65, 2]}

    pipico[l]:
      type: hist2d
      arange: {'ppc_l:pp1': [0, 12000, 100], 'ppc_l:pp2': [0, 12000, 100]}      

    # pipico[l]_gated:
    #   type: hist2d_func
    #   func_x: {name: dream.custom.filter.a_gatedOn_bc, args1:['ppc_l:pp1', 'hit_l:y', 'hit_l:z'], args2:[-6, 6, -6, 6]}
    #   func_y: {name: dream.custom.filter.a_gatedOn_bc, args1:['ppc_l:pp2', 'hit_l:y', 'hit_l:z'], args2:[-6, 6, -6, 6]}
    #   arange_var: {'gated t1': [0, 12000, 100], 'gated t2': [0, 12000, 100]}         
    
    x-t[l]:
      type: hist2d
      arange: {'hit_l:t': [0, 15000, 10], 'hit_l:y': [-65, 65, 2]}
    
    y-t[l]:
      type: hist2d
      arange: {'hit_l:t': [0, 15000, 10], 'hit_l:z': [-65, 65, 2]}
      
    x-y[l]_gated:
      type: hist2d_func
      func_x: {name: dream.custom.filter.a_gatedOn_b, args1:['hit_l:y', 'hit_l:t'], args2:[10000, 11000]}
      func_y: {name: dream.custom.filter.a_gatedOn_b, args1:['hit_l:z', 'hit_l:t'], args2:[10000, 11000]}
      arange_var: {'gated y': [-65, 65, 1], 'gated z': [-65, 65, 1]}         

    t[l]_gated:
      type: hist1d_func
      func: {name: dream.custom.filter.a_gatedOn_bc, args1:['hit_l:t', 'hit_l:y', 'hit_l:z'], args2:[-10, 10, -10, 10]}
      arange_var: {'gated t': [0, 15000, 1]}  

    y-t[l]_gated:
      type: hist2d_func
      func_x: {name: dream.custom.filter.a_gatedOn_b, args1:['hit_l:t', 'hit_l:y'], args2:[-5, 5]}
      func_y: {name: dream.custom.filter.a_gatedOn_b, args1:['hit_l:z', 'hit_l:y'], args2:[-5, 5]}
      arange_var: {'gated t': [0, 15000, 10], 'gated y': [-65, 65, 1]}    

    x-t[l]_gated:
      type: hist2d_func
      func_x: {name: dream.custom.filter.a_gatedOn_b, args1:['hit_l:t', 'hit_l:z'], args2:[-5, 5]}
      func_y: {name: dream.custom.filter.a_gatedOn_b, args1:['hit_l:y', 'hit_l:z'], args2:[-5, 5]}
      arange_var: {'gated t': [0, 15000, 10], 'gated z': [-65, 65, 1]}  

    atm_sig_bkg:
      type: sigbkg1d
      plot_type: singleline_func 
      opt_type: div
      window: 1000
      func_sig: {name: dream.custom.filter.atm, args1: ['atm:line', 'bld:xgmd', 'timing:280'], args2: [0.005, 1]}
      func_bkg: {name: dream.custom.filter.atm, args1: ['atm:line', 'bld:xgmd', 'timing:281'], args2: [0, 1]}      

    atm_sig_bkg_g:
      type: sigbkg1d
      plot_type: singleline_func 
      opt_type: div
      window: 1000
      func_sig: {name: dream.custom.filter.atm, args1: ['atm:gline', 'bld:xgmd', 'timing:280'], args2: [0.005, 1]}
      func_bkg: {name: dream.custom.filter.atm, args1: ['atm:gline', 'bld:xgmd', 'timing:281'], args2: [0, 1]}    
      
#    wf[s]:
#      type: multiline
#      y_offset: 100
#      var: ['wf_s:mcp', 'wf_s:u1', 'wf_s:u2', 'wf_s:v1', 'wf_s:v2', 'wf_s:w1', 'wf_s:w2']
      
#    padded[s]:
#      type: multiline
#      y_offset: 1600
#      var: ['pdd_s:mcp', 'pdd_s:u1', 'pdd_s:u2', 'pdd_s:v1', 'pdd_s:v2', 'pdd_s:w1', 'pdd_s:w2']      
      
#    n[s]_rollavg:
#      type: rollavg
#      var: 'hit_s:n'
#      window: {'w1':1000, 'w2':1000} 
     
#    t[s]:
#      type: hist1d
#      arange: {'hit_s:t': [0, 15000, 5]}
    
#    x-y[s]:
#      type: hist2d
#      arange: {'hit_s:y': [-65, 65, 2], 'hit_s:z': [-65, 65, 2]}
    
#    x-t[s]:
#      type: hist2d
#      arange: {'hit_s:t': [0, 15000, 10], 'hit_s:y': [-65, 65, 2]}
    
#    y-t[s]:
#      type: hist2d
#      arange: {'hit_s:t': [0, 15000, 10], 'hit_s:z': [-65, 65, 2]}



